package org.difftest.model;

public enum DTFailureReason {
    NONE,
    MAIN_CLASS_NOT_FOUND,
    COMPILER_SYMBOL_NOT_FOUND,
    COMPILER_MISSING_RETURN,
    COMPILER_LAMBDA_CAPTURE_EFFECTIVELY_FINAL,
    COMPILER_LAMBDA_MISSING_RETURN_VALUE,
    COMPILER_UNREACHABLE_CODE,
    PROCESS_INTERRUPTED
}
